name: Assign the author to the assignee

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  assign-author:
    runs-on: ubuntu-latest

    steps:
      - uses: toshimaru/auto-author-assign@v2.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
