name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: dry-run
        required: true
        type: boolean

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: npm install

      - name: Verifying the signatures
        run: npm audit signatures

      - name: Release
        run: npm run release ${{ github.event.inputs.dry_run == 'true' && '-- --dry-run' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
